"""Bluetooth auto-pair state machine labels."""

from __future__ import annotations

from enum import Enum


class PairState(str, Enum):
    INIT = "INIT"
    CLEANING_GHOST_PAIR = "CLEANING_GHOST_PAIR"
    RESETTING_ADAPTER = "RESETTING_ADAPTER"
    RESTARTING_SERVICES = "RESTARTING_SERVICES"
    WAITING_FOR_DEVICE_PAIRING_MODE = "WAITING_FOR_DEVICE_PAIRING_MODE"
    DISCOVERING = "DISCOVERING"
    CANDIDATE_FOUND = "CANDIDATE_FOUND"
    PAIRABLE_CANDIDATE_FOUND = "PAIRABLE_CANDIDATE_FOUND"
    PAIR_REQUESTED = "PAIR_REQUESTED"
    PAIRING = "PAIRING"
    PAIRED = "PAIRED"
    AUDIO_ENDPOINT_WAIT = "AUDIO_ENDPOINT_WAIT"
    AUDIO_ENDPOINT_READY = "AUDIO_ENDPOINT_READY"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
